### ISSUE TITLE
Some icustay_ids in TOTALBALEVENTS displaying null instead of the ID

### ISSUE THREAD

**Issue by tompollard** [mimic2/v3.0#9]
Some records have been assigned null values, but it looks like it would be more appropriate to assign an icustay_id.

For example, see subject_id 6204. The last charted event has an icustay_id of null, when it looks like icustay_id = 7720 would be more appropriate (based on previous events).

**Comment by mornin** [comment]
This was caused by the fact that all TOTALBALEVENTS records were time stamped at 11am, although they are actually daily records (see issue #10 ). Thus, the patient may have discharged by 11am and caused a mismatched between ICUSTAY_ID and TOTALBALEVENTS records. The can be fix as (code included in  v3.0/code/mimic2v30_beta_utc.sql):

with temp as
(select distinct
a.subject_id
, a.icustay_id
--, a.charttime
--, b.charttime
, b.TOTALBALEVENTSDATAID
from MIMIC2V30B.totalbalevents a
join MIMIC2V30B.totalbalevents b 
  on a.subject_id=b.subject_id 
  and a.cumitemid=b.cumitemid 
  and a.icustay_id is not null
  and b.icustay_id is null
  and b.charttime <= a.charttime+1
)

, totalbalevents_new as
(select
a.SUBJECT_ID
,case  when a.ICUSTAY_ID is null then b.ICUSTAY_ID else a.ICUSTAY_ID end as ICUSTAY_ID
,a.CHARTTIME
,a.ELEMID
,a.REALTIME
,a.CGID
,a.CUID
,a.ITEMID
,a.LABEL
,a.VOLUME
,a.CUMITEMID
,a.CUMLABEL
,a.CUMVOLUME
,a.UOM
,a.ACCUMPERIOD
,a.APPROX
,a.RESET
,a.STOPPED
,a.TOTALBALEVENTSDATAID
from MIMIC2V30B.totalbalevents a
left join temp b on a.TOTALBALEVENTSDATAID=b.TOTALBALEVENTSDATAID
)

--select count(*) from totalbalevents_new where icustay_id is null;
select * from totalbalevents_new;

**Comment by tompollard** [comment]
Thanks @mornin. Probably not important, but just in case it matters - the charttime timestamps in TOTALBALEVENTS are 11pm, rather than 11am.

**Comment by tompollard** [comment]
Updated in MIMIC2V30B_UTC.TOTALBALEVENTS, so will be fixed in the v3.0 release.
